
build:
  version: "1.1"

accounts:
  message: "Welcome to ASPL_bank account related Production APIs"
  contactDetails:
    name: "Tejas - Product Lead"
    email: "tejas@audilitycssolutions"
  onCallSupport:
    - 9685745869
    - 9475869646