
build:
  version: "2.1"

cards:
  message: "Welcome to ASPL_bank Cards related QA APIs"
  contactDetails:
    name: "Rituraj Y - QA Lead"
    email: "rituraj.y@audilitycssolutions"
  onCallSupport:
    - 8546975854
    - 8754965875